=== donthomaspj/xml-project1/DonThomas_XMLProject/project.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="timeTable">
		<xs:complexType>
			<xs:all>

				<!--Student name-->
				<xs:element name="studentName" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="name"/>
					</xs:complexType>
				</xs:element>

				<!--Student id-->
				<xs:element name="studentId" type="xs.integer"  maxOccurs="1"/>

				<!--Program-->
				<xs:element name="program" minOccurs="0"  maxOccurs="1" />

				<!--school name-->
				<xs:element name="school" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="schoolName"/>
					</xs:complexType>
				</xs:element>

				<!--Course term-->
				<xs:element name="term" maxOccurs="1"/>

				<!--Week days-->
				<xs:element name="week">
					<xs:complexType>
						<xs:all>

							<!--monday-->
							<xs:element name="day1">
								<xs:complexType>
									<xs:all>
										<!--week name-->
										<xs:element name="dayName">
											<xs:simpleType>
												<xs:restriction base="xs:ID">
													<xs:pattern value="Monday|Tuesday|Wedesday|Thursday|Friday"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<!--hours-->
										<xs:element name="hour">
											<xs:complexType>
												<xs:all>

													<!--starttime-->
													<xs:element name="startTime">
														<xs:simpleType>
															<xs:restriction base="xs:integer">
																<xs:pattern value="800|900|1000|1100|1200|1300|1400|1500|1600|1700|1800|1900|2000" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>

													<!--course-->
													<xs:element name="course">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:pattern value="[A-Z]{4}-[0-9]{4}"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>

													<!--room-->
													<xs:element name="room"/>

												</xs:all>
											</xs:complexType>
										</xs:element>

									</xs:all>
								</xs:complexType>

							</xs:element>

							<!--tuesday-->
							<xs:element name="day2">
								<xs:complexType>
									<xs:all>
										<!--week name-->
										<xs:element name="dayName">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="Monday|Tuesday|Wedesday|Thursday|Friday"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<!--hours-->
										<xs:element name="hour">
											<xs:complexType>
												<xs:all>

													<!--starttime-->
													<xs:element name="startTime">
														<xs:simpleType>
															<xs:restriction base="xs:integer">
																<xs:pattern value="800|900|1000|1100|1200|1300|1400|1500|1600|1700|1800|1900|2000" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>

													<!--course-->
													<xs:element name="course">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:pattern value="[A-Z]{4}-[0-9]{4}"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>

													<!--room-->
													<xs:element name="room"/>

												</xs:all>
											</xs:complexType>
										</xs:element>

									</xs:all>
								</xs:complexType>

							</xs:element>

							<!--wednesday-->
							<xs:element name="day3">
								<xs:complexType>
									<xs:all>
										<!--week name-->
										<xs:element name="dayName">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="Monday|Tuesday|Wedesday|Thursday|Friday"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<!--hours-->
										<xs:element name="hour">
											<xs:complexType>
												<xs:all>

													<!--starttime-->
													<xs:element name="startTime">
														<xs:simpleType>
															<xs:restriction base="xs:integer">
																<xs:pattern value="800|900|1000|1100|1200|1300|1400|1500|1600|1700|1800|1900|2000" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>

													<!--course-->
													<xs:element name="course">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:pattern value="[A-Z]{4}-[0-9]{4}"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>

													<!--room-->
													<xs:element name="room"/>

												</xs:all>
											</xs:complexType>
										</xs:element>

									</xs:all>
								</xs:complexType>

							</xs:element>

							<!--thursday-->
							<xs:element name="day4">
								<xs:complexType>
									<xs:all>
										<!--week name-->
										<xs:element name="dayName">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="Monday|Tuesday|Wedesday|Thursday|Friday"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<!--hours-->
										<xs:element name="hour">
											<xs:complexType>
												<xs:all>

													<!--starttime-->
													<xs:element name="startTime">
														<xs:simpleType>
															<xs:restriction base="xs:integer">
																<xs:pattern value="800|900|1000|1100|1200|1300|1400|1500|1600|1700|1800|1900|2000" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>

													<!--course-->
													<xs:element name="course">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:pattern value="[A-Z]{4}-[0-9]{4}"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>

													<!--room-->
													<xs:element name="room"/>

												</xs:all>
											</xs:complexType>
										</xs:element>

									</xs:all>
								</xs:complexType>

							</xs:element>


							<!--friday-->
							<xs:element name="day5">
								<xs:complexType>
									<xs:all>
										<!--week name-->
										<xs:element name="dayName">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="Monday|Tuesday|Wedesday|Thursday|Friday"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<!--hours-->
										<xs:element name="hour">
											<xs:complexType>
												<xs:all>

													<!--starttime-->
													<xs:element name="startTime">
														<xs:simpleType>
															<xs:restriction base="xs:integer">
																<xs:pattern value="800|900|1000|1100|1200|1300|1400|1500|1600|1700|1800|1900|2000" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>

													<!--course-->
													<xs:element name="course">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:pattern value="[A-Z]{4}-[0-9]{4}"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>

													<!--room-->
													<xs:element name="room"/>

												</xs:all>
											</xs:complexType>
										</xs:element>

									</xs:all>
								</xs:complexType>

							</xs:element>

						</xs:all>
					</xs:complexType>
				</xs:element>
				
			</xs:all>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== donthomaspj/xml-project1/DonThomas_XMLProject/project.xml
<?xml version="1.0" encoding="utf-8"?>
<timeTable 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="project.xsd">
	<studentName name ="Don Thomas"></studentName>
	<studentId>900001</studentId>
	<program>Computer Science</program>
	<school schoolName="Fanshawe College"/>
	<term>W2021</term>
	<week>
		<day1>
			<dayName>Monday</dayName>
			<hour>
				<startTime>1900</startTime>
				<course>INFO-1122</course>
				<room>R1122</room>
			</hour>
			<hour>
				<startTime>1000</startTime>
				<course>INFO-1234</course>
				<room>R0123</room>
			</hour>
			<hour>
				<startTime>1500</startTime>
				<course>INFO-2233</course>
				<room>R0124</room>
			</hour>
		</day1>
		<day2>
			<dayName>Tuesday</dayName>
			<hour>
				<startTime>800</startTime>
				<course>INFO-1122</course>
				<room>R0122</room>
			</hour>
			<hour>
				<startTime>1000</startTime>
				<course>INFO-1234</course>
				<room>R0134</room>
			</hour>
			<hour>
				<startTime>1600</startTime>
				<course>INFO-2233</course>
				<room>R0024</room>
			</hour>
		</day2>
		<day3>
			<dayName>Wedesday</dayName>
			<hour>
				<startTime>1100</startTime>
				<course>INFO-1122</course>
				<room>R0144</room>
			</hour>
			<hour>
				<startTime>1400</startTime>
				<course>INFO-2233</course>
				<room>R0155</room>
			</hour>
			<hour>
				<startTime>1800</startTime>
				<course>INFO-1234</course>
				<room>R003</room>
			</hour>
		</day3>
		<day4>
			<dayName>Thursday</dayName>
			<hour>
				<startTime>1300</startTime>
				<course>INFO-2233</course>
				<room>R0133</room>
			</hour>
			<hour>
				<startTime>1400</startTime>
				<course>INFO-1122</course>
				<room>R0043</room>
			</hour>
			<hour>
				<startTime>1500</startTime>
				<course>INFO-1234</course>
				<room>R0111</room>
			</hour>
		</day4>
		<day5>
			<dayName>Friday</dayName>
			<hour>
				<startTime>1200</startTime>
				<course>INFO-2233</course>
				<room>R0111</room>
			</hour>
			<hour>
				<startTime>1300</startTime>
				<course>INFO-2222</course>
				<room>R0051</room>
			</hour>
			<hour>
				<startTime>1400</startTime>
				<course>INFO-2233</course>
				<room>R011</room>
			</hour>
			<hour>
				<startTime>2000</startTime>
				<course>INFO-3333</course>
				<room>R0166</room>
			</hour>
		</day5>
	</week>
	
</timeTable>

=== donthomaspj/xml-project1/DonThomas_XMLProject/project2.xml
<?xml version="1.0" encoding="utf-8"?>
<timeTable 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="project.xsd">
	<studentName name ="Alan Rocky"></studentName>
	<studentId>901011</studentId>
	<program>Economics</program>
	<school schoolName="Western College"/>
	<term>W2020</term>
	<week>
		<day1>
			<dayName>Monday</dayName>
			<hour>
				<startTime>1000</startTime>
				<course>ECON-1122</course>
				<room>R1122</room>
			</hour>
			<hour>
				<startTime>1200</startTime>
				<course>ECON-1234</course>
				<room>R0123</room>
			</hour>
			<hour>
				<startTime>1500</startTime>
				<course>ECON-2233</course>
				<room>R0124</room>
			</hour>
		</day1>
		<day2>
			<dayName>tuesday</dayName>
			<hour>
				<startTime>800</startTime>
				<course>ECON-1122</course>
				<room>R0122</room>
			</hour>
			<hour>
				<startTime>1100</startTime>
				<course>ECON-1234</course>
				<room>R0134</room>
			</hour>
			<hour>
				<startTime>1700</startTime>
				<course>ECON-2233</course>
				<room>R0024</room>
			</hour>
		</day2>
		<day3>
			<dayName>Wedesday</dayName>
			<hour>
				<startTime>1400</startTime>
				<course>ECON-1122</course>
				<room>R0144</room>
			</hour>
			<hour>
				<startTime>1600</startTime>
				<course>ECON-2233</course>
				<room>R0155</room>
			</hour>
			<hour>
				<startTime>2000</startTime>
				<course>ECON-1234</course>
				<room>R003</room>
			</hour>
		</day3>
		<day4>
			<dayName>Thursday</dayName>
			<hour>
				<startTime>1500</startTime>
				<course>ECON-2233</course>
				<room>R0133</room>
			</hour>
			<hour>
				<startTime>1200</startTime>
				<course>ECON-1122</course>
				<room>R0043</room>
			</hour>
			<hour>
				<startTime>1300</startTime>
				<course>ECON-1234</course>
				<room>R0111</room>
			</hour>
		</day4>
		<day5>
			<dayName>friday</dayName>
			<hour>
				<startTime>1400</startTime>
				<course>ECON-2233</course>
				<room>R0111</room>
			</hour>
			<hour>
				<startTime>1300</startTime>
				<course>ECON-2222</course>
				<room>R0051</room>
			</hour>
			<hour>
				<startTime>1600</startTime>
				<course>ECON-2233</course>
				<room>R011</room>
			</hour>
			<hour>
				<startTime>2000</startTime>
				<course>ECON-3333</course>
				<room>R0166</room>
			</hour>
		</day5>
	</week>

</timeTable>
